learning_site/courses/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url

from . import views


app_name = "courses"

urlpatterns = [
	path('', views.course_list, name="course_list"),
	path('<course_pk>/<step_pk>/', views.step_detail, name="step_detail"),
	path('<int:pk>/', views.course_detail, name="course_detail"),
]

learning_site/learning_site/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import url

from . import views

urlpatterns = [
    path('', views.hello_world, name='index'),
    path('suggest/', views.suggestion_view, name='suggestion'),
	path('courses/', include('courses.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

learning_site/courses/models.py
from django.db import models

# Create your models here.
class Course(models.Model):
	created_at = models.DateTimeField(auto_now_add=True)
	title = models.CharField(max_length=255)
	description = models.TextField()

	def __str__(self):
		return self.title



class Step(models.Model):
	title = models.CharField(max_length=255)
	description = models.TextField()
	content = models.TextField(blank=True, default='')
	order = models.IntegerField(default=0)
	course = models.ForeignKey(Course, on_delete=models.CASCADE)

	class Meta:
		ordering = ['order',]

	def __str__(self):
		return self.title		

learning_site/learning_site/forms.py
from django import forms


class SuggestionForm(forms.Form):
	name = forms.CharField()
	email = forms.EmailField()
	suggestion = forms.CharField(widget=forms.Textarea)

learning_site/courses/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

from .models import Course, Step

# Create your views here.
def course_list(request):
	courses = Course.objects.all()
	email = 'questions@learning_site.com'
	return render(request, "courses/course_list.html", {'courses':courses, 'email':email})



def course_detail(request, pk):
	course = get_object_or_404(Course, pk=pk)
	return render(request, 'courses/course_detail.html', {'course':course})


def step_detail(request, course_pk, step_pk):
	step = get_object_or_404(Step, course_id=course_pk, pk=step_pk)
	return render(request, 'courses/step_detail.html', {'step':step})

learning_site/learning_site/views.py
from django.shortcuts import render


from . import forms

def hello_world(request):
	return render(request, "home.html")

def suggestion_view(request):
	form = forms.SuggestionForm()
	if request.method == 'POST':
		form = forms.SuggestionForm(request.POST)
		if form.is_valid():
			print("Good form!")
	return render(request, 'suggestion_form.html', {'form':form})

learning_site/courses/templates/courses/course_detail.html
{% extends "layout.html" %}
{% load humanize %}


{% block title %}{{ course.title }}{% endblock %}

{% block content %}
<article>
	<h2>{{ course.title }}</h2>
	{{ course.description }}
	<p>These are the {{ course.step_set.count|apnumber }} step{{ course.step_set.all|pluralize }} in this course: {{ course.step_set.all|join:", " }}</p>
	<section>
		{% for step in course.step_set.all %}
			<h3>
				<a href="{% url 'courses:step_detail' course_pk=step.course.pk step_pk=step.pk %}">{{ step.title }}</a>
			</h3>
			{{ step.description }}
		{% endfor %}
	</section>
</article>
{% endblock %}

learning_site/courses/templates/courses/course_list.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block static %}<link rel="stylesheet" href="{% static 'courses/css/courses.css' %}">{% endblock %}
{% block title %}Available Courses{% endblock %}
{% block content %}
<div class="cards">
	{% for course in courses %}
	<div class="card">	
		<header><a href="{% url 'courses:course_detail' pk=course.pk %}">{{ course.title }}</a></header>
		<div class="card-copy">
			{% if course.description|wordcount <= 5 %}
				{{ course.description }}
			{% else %}		
				{{ course.description|truncatewords:5 }}	
				<a href="{% url 'courses:course_detail' pk=course.pk %}">Read more..</a>
			{% endif %}
			<div>created on: {{ course.created_at|date:"F j, Y" }}</div>
		</div>
	</div>	
	{% endfor %}
	<div>Have questions? Contact us!{{ email|urlize }}</a></div>
</div>
{% endblock %}

learning_site/courses/templates/courses/course_nav.html
{% for course in courses %}
	<div><a href="{% url 'courses:course_detail' pk=course.pk %}">{{ course.title }}</a></div>
{% endfor %}

learning_site/courses/templates/courses/step_detail.html
{% extends "layout.html" %}


{% block title %} {{ step.title }} - {{step.course.title}}{% endblock %}


{% block content %}
<article>
	<h2><a href="{% url 'courses:course_detail' pk=step.course.pk %}">{{step.course.title}}</a></h2>
	<h3>{{ step.title }}</h3>

	{% with con=step.content %}
	{{ con|linebreaks }} content:{{ con|wordcount }}
	{% endwith %}
</article>
{% endblock %}

learning_site/templates/home.html
{% extends "layout.html" %}

{% block title %}Well hello there!{% endblock %}


{% block content %}
<h1>WELCOME</h1>
{% endblock %}

learning_site/templates/layout.html
{% load static from staticfiles %}
{% load course_extras %}

<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %}{% endblock %}</title>
		<link rel="stylesheet" href="{% static 'css/layout.css' %}">
		{% block static %}{% endblock %}
	</head>
	<body>
		<div class="site-container">
			<div>{% nav_courses_list %}</div>
			<nav>
				<a href="{% url 'index' %}">HOME</a>
				<a href="{% url 'courses:course_list' %}">COURSE LIST</a>
			</nav>
			<p>Don't miss our latest course!, {% newest_course %}</p>
			{% block content %}{% endblock %}
		</div>
	</body>
</html>

learning_site/templates/suggestion_form.html
{% extends "layout.html" %}

{% block title %}Suggest an idea{% endblock %}


{% block content %}
	<div class="row">
		<form action="" method="POST">
			{{ form.as_p }}
			{% csrf_token %}
			<input type="submit">
		</form>
	</div>
{% endblock %}